# Site settings
title: Storage Lock
email: storage-lock@users.noreply.github.com
description: >-
  Storage Lock — 一个存储后端无关的分布式锁框架，基于 Go 语言实现，
  通过抽象 Storage 接口，支持任何可分布式访问的存储介质来实现分布式锁。
baseurl: ""
url: "https://storage-lock.github.io"
github_username: storage-lock

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark

header_pages:
  - about.markdown
